### ISSUE TITLE
[13] "Socialism" Search 

### ISSUE THREAD

**Issue by jonhudgins** [jonhudgins/A4-Group-Project-#9]
As a researcher,
I want to read a clear analysis of how frequently the word "socialism" is used in right wing and left wing media in the united states,
So that I can use it in my research

**Comment by inayat26** [comment]
- [ ] Run queries and download CSVs from media cloud

- [ ] Write analysis in a text editor 

- [ ] Mark up analysis in HTML

- [ ] Link css stylesheet to HTML

- [ ] Add MVP1 visualisations

- [ ] Merge to master

**Comment by n-anw** [comment]
Inayat to write an MVP of the analysis
Nick to do the HTML
